name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: wx257osn2/cxx_environment@v2
      with:
        url_format: 'https://github.com/wx257osn2/qoi-benchmark/releases/download/{}'
        version: image-v20250302
    - uses: actions/cache/restore@v4
      id: cached
      with:
        path: images
        key: key
    - name: get benchmark suite
      if: steps.cached.outputs.cache-hit != 'true'
      shell: bash
      run: curl https://qoiformat.org/benchmark/qoi_benchmark_suite.tar | tar x
    - uses: actions/cache/save@v4
      if: steps.cached.outputs.cache-hit != 'true' && matrix.os == 'ubuntu-24.04'
      with:
        path: images
        key: ${{ steps.cached.outputs.cache-primary-key }}
    - name: build
      shell: bash
      run: cxx-env-run make -j
    - name: run
      shell: bash
      run: benchmark/bin/qoibench 10 images --threads=0
