name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: wx257osn2/cxx_environment@v2
      with:
        url_format: 'https://github.com/wx257osn2/qoi-benchmark/releases/download/{}'
        version: image-v20250302
    - uses: actions/cache@v4
      id: cached
      with:
        path: images
        key: key
    - name: get benchmark suite
      if: steps.cached.outputs.cache-hit != 'true'
      shell: bash
      run: curl https://qoiformat.org/benchmark/qoi_benchmark_suite.tar | tar x
    - name: build
      shell: bash
      run: cxx-env-run make -j
    - name: run
      shell: bash
      run: benchmark/bin/qoibench 10 images --threads=0
