name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt_lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: wx257osn2/cxx_environment@v2
      with:
        url_format: 'https://github.com/wx257osn2/qoi-benchmark/releases/download/{}'
        version: image-v20250302
    - name: run
      shell: bash
      run: |
        pushd qoi-rust
        cxx-env-run cargo fmt -- --check
        cxx-env-run cargo clippy
        popd
        pushd rapid-qoi
        cxx-env-run cargo fmt -- --check
        cxx-env-run cargo clippy
        popd
