name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fmt_lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: Swatinem/rust-cache@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: run
      shell: bash
      run: |
        pushd qoi-rust
        cargo fmt -- --check
        cargo clippy
        popd
        pushd rapid-qoi
        cargo fmt -- --check
        cargo clippy
        popd
